package com.rules_samochody
import javax.swing.JOptionPane

declare Question_and_Answer
	question: String
	answer: String
end

//main question
rule "Why do you want a classic?"
    when
    then
        Object[] possibleValues = { "Reliability and convenience bore me", 
        							"I guess I'm making some kind of statement about something", 
        							"New cars have no soul",
        							"I prefer the style",
        							"Love speed, hate safety" };
		Object selectedValue = JOptionPane.showInputDialog(null,"Why do you want a classic? Choose one",
								 "Input",JOptionPane.INFORMATION_MESSAGE, null,possibleValues, possibleValues[0]);
		Question_and_Answer q1=new Question_and_Answer();
		q1.setQuestion("Why do you want a classic?");
		q1.setAnswer(selectedValue.toString());
		insert(q1);
end

//1st path
rule "Reliability and convenience bore me"
	when 
		q: Question_and_Answer(question=="Why do you want a classic?" && answer=="Reliability and convenience bore me")
	then
		Object[] possibleValues = { "I want to know how cars work", 
        							"I'm erotically drawn to tow trucks and freeway how cars work"};
        Object selectedValue = JOptionPane.showInputDialog(null,"Oh yeah? Why's that? Choose one",
								 "Input",JOptionPane.INFORMATION_MESSAGE, null,possibleValues, possibleValues[0]);
		Question_and_Answer q1=new Question_and_Answer();
		q1.setQuestion("Oh yeah? Why's that?");
		q1.setAnswer(selectedValue.toString());
		insert(q1);
end



rule "I want to know how cars work"
	when
		q: Question_and_Answer(question=="Oh yeah? Why's that?" && answer=="I want to know how cars work")
	then
		Object[] possibleValues = { "Sounds good", 
        							"Not that archaic",
        							"More archaic"};
        Object selectedValue = JOptionPane.showInputDialog(null,"So, something really simple? Choose one",
								 "Input",JOptionPane.INFORMATION_MESSAGE, null,possibleValues, possibleValues[0]);
		Question_and_Answer q1=new Question_and_Answer();
		q1.setQuestion("So, something really simple?");
		q1.setAnswer(selectedValue.toString());
		insert(q1);
end

rule "I'm erotically drawn to tow trucks and freeway how cars work"
	when
		q: Question_and_Answer(question=="Oh yeah? Why's that?" && answer=="I'm erotically drawn to tow trucks and freeway how cars work")
	then
		Object[] possibleValues = { "Yes","Also really lovely"};
        Object selectedValue = JOptionPane.showInputDialog(null,"Ok. Should it be pretty quick? Choose one",
								 "Input",JOptionPane.INFORMATION_MESSAGE, null,possibleValues, possibleValues[0]);
		Question_and_Answer q1=new Question_and_Answer();
		q1.setQuestion("Ok. Should it be pretty quick?");
		q1.setAnswer(selectedValue.toString());
		insert(q1);
end

rule "Yes"
	when
		q: Question_and_Answer(question=="Ok. Should it be pretty quick?" && answer=="Yes")
	then
		JOptionPane.showInternalMessageDialog(null, "LOTUS ELAN","information", JOptionPane.INFORMATION_MESSAGE);
end

rule "Also really lovely"
	when
		q: Question_and_Answer(question=="Ok. Should it be pretty quick?" && answer=="Also really lovely")
	then
		JOptionPane.showInternalMessageDialog(null, "ALFA ROMEO GIULIA SUPER","information", JOptionPane.INFORMATION_MESSAGE);
end

rule "Sounds good"
	when
		q: Question_and_Answer(question=="So, something really simple?" && answer=="Sounds good")
	then
		JOptionPane.showInternalMessageDialog(null, "HONDA CIVIC, WILLYS JEEP,VW THING, CITROEN 2CV", "information",JOptionPane.INFORMATION_MESSAGE);
end

rule "Not that archaic"
	when
		q: Question_and_Answer(question=="So, something really simple?" && answer=="Not that archaic")
	then
		JOptionPane.showInternalMessageDialog(null, "FORD MODEL A", "information",JOptionPane.INFORMATION_MESSAGE);
end

rule "More archaic"
	when
		q: Question_and_Answer(question=="So, something really simple?" && answer=="More archaic")
	then
		JOptionPane.showInternalMessageDialog(null, "FORD MODEL T","information", JOptionPane.INFORMATION_MESSAGE);
end

//2nd path
rule "I guess I'm making some kind of statement about something"
	when 
		q: Question_and_Answer(question=="Why do you want a classic?" && answer=="I guess I'm making some kind of statement about something")
	then
		 Object[] possibleValues = { "I'm really rich, but like to pretend I'm still hippie",
		 							 "I run an nyc-themed diner in Las Vegas",
		 							 "The mothership left me in Paris",
		 							 "I live dangerously and nader can suck it",
		 							 "I'm kook. An american kook",
		 							 "I take driving seriously and have the gloves to prove it",
		 							 "My wallet is on a chain",
		 							 "I'm a refugee from an alternate future with zeppelins and shit",
		 							 "I hate people knowing what I drive",
		 							 "I wanted a motocycle but I have no balance",
		 							 "I like being part of a massive automotive subculture",
		 							 "I will only drive vehicles with two distinct luggage areas"};
		 Object selectedValue = JOptionPane.showInputDialog(null,"Great, what statement? Choose one",
								 "Input",JOptionPane.INFORMATION_MESSAGE, null,possibleValues, possibleValues[0]);
		Question_and_Answer q1=new Question_and_Answer();
		q1.setQuestion("Great, what statement?");
		q1.setAnswer(selectedValue.toString());
		insert(q1);
end

rule "I'm really rich, but like to pretend I'm still hippie"
	when
		q: Question_and_Answer(question=="Great, what statement?" && answer=="I'm really rich, but like to pretend I'm still hippie")
	then
		JOptionPane.showInternalMessageDialog(null, "VW TYPE2 MICROBUS", "information",JOptionPane.INFORMATION_MESSAGE);
end

rule "I run an nyc-themed diner in Las Vegas"
	when
		q: Question_and_Answer(question=="Great, what statement?" && answer=="I run an nyc-themed diner in Las Vegas")
	then
		JOptionPane.showInternalMessageDialog(null, "CHECKER MARATHON", "information",JOptionPane.INFORMATION_MESSAGE);
end

rule "The mothership left me in Paris"
	when
		q: Question_and_Answer(question=="Great, what statement?" && answer=="The mothership left me in Paris")
	then
		JOptionPane.showInternalMessageDialog(null, "CITROEN SM", "information",JOptionPane.INFORMATION_MESSAGE);
end

rule "I live dangerously and nader can suck it"
	when
		q: Question_and_Answer(question=="Great, what statement?" && answer=="I live dangerously and nader can suck it")
	then
		JOptionPane.showInternalMessageDialog(null, "CHEVY CORVAIR", "information",JOptionPane.INFORMATION_MESSAGE);
end

rule "I'm kook. An american kook"
	when
		q: Question_and_Answer(question=="Great, what statement?" && answer=="I'm kook. An american kook")
	then
		JOptionPane.showInternalMessageDialog(null, "AMC PACER, AMC GREMLIN, AMC AMX", "information",JOptionPane.INFORMATION_MESSAGE);
end

rule "I take driving seriously and have the gloves to prove it"
	when
		q: Question_and_Answer(question=="Great, what statement?" && answer=="I take driving seriously and have the gloves to prove it")
	then
		JOptionPane.showInternalMessageDialog(null, "BMW E30, PORSHE 911", "information",JOptionPane.INFORMATION_MESSAGE);
end

rule "My wallet is on a chain"
	when
		q: Question_and_Answer(question=="Great, what statement?" && answer=="My wallet is on a chain")
	then
		Object[] possibleValues = { "Yes",
									"Not for style, I'm tired of losing it"};
        Object selectedValue = JOptionPane.showInputDialog(null,"Are you here for style? Choose one",
								 "Input",JOptionPane.INFORMATION_MESSAGE, null,possibleValues, possibleValues[0]);
		Question_and_Answer q1=new Question_and_Answer();
		q1.setQuestion("Are you here for style?");
		q1.setAnswer(selectedValue.toString());
		insert(q1);
end

rule "Yes_2"
	when
		q: Question_and_Answer(question=="Are you here for style?" && answer=="Yes")
	then
		JOptionPane.showInternalMessageDialog(null, "FORD FALCON, PLYMOUTH VALIANT", "information",JOptionPane.INFORMATION_MESSAGE);
end

rule "Not for style, I'm tired of losing it"
	when
		q: Question_and_Answer(question=="Are you here for style?" && answer=="Not for style, I'm tired of losing it")
	then
		JOptionPane.showInternalMessageDialog(null, "RAMBLER AMERICAN", "information",JOptionPane.INFORMATION_MESSAGE);
end

rule "I'm a refugee from an alternate future with zeppelins and shit"
	when
		q: Question_and_Answer(question=="Great, what statement?" && answer=="I'm a refugee from an alternate future with zeppelins and shit")
	then
		JOptionPane.showInternalMessageDialog(null, "TATRA T87", "information",JOptionPane.INFORMATION_MESSAGE);
end

rule "I hate people knowing what I drive"
	when
		q: Question_and_Answer(question=="Great, what statement?" && answer=="I hate people knowing what I drive")
	then
		JOptionPane.showInternalMessageDialog(null, "STERLING 825, MITSUBISHI STARION, ISUZU I-MARK", "information",JOptionPane.INFORMATION_MESSAGE);
end

rule "I wanted a motocycle but I have no balance"
	when
		q: Question_and_Answer(question=="Great, what statement?" && answer=="I wanted a motocycle but I have no balance")
	then
		JOptionPane.showInternalMessageDialog(null, "LOTUS 7", "information",JOptionPane.INFORMATION_MESSAGE);
end

rule "I like being part of a massive automotive subculture"
	when
		q: Question_and_Answer(question=="Great, what statement?" && answer=="I like being part of a massive automotive subculture")
	then
		JOptionPane.showInternalMessageDialog(null, "VW BETTLE, MGB, DATSUN 240Z, VOLVO 240 ", "information",JOptionPane.INFORMATION_MESSAGE);
end

rule "I will only drive vehicles with two distinct luggage areas"
	when
		q: Question_and_Answer(question=="Great, what statement?" && answer=="I will only drive vehicles with two distinct luggage areas")
	then
		Object[] possibleValues = { "No",
									"Yes"};
        Object selectedValue = JOptionPane.showInputDialog(null,"Something faster than VW TYPE III? Choose one",
								 "Input",JOptionPane.INFORMATION_MESSAGE, null,possibleValues, possibleValues[0]);
		Question_and_Answer q1=new Question_and_Answer();
		q1.setQuestion("Something faster than VW TYPE III?");
		q1.setAnswer(selectedValue.toString());
		insert(q1);
end

rule "No"
	when 
		q: Question_and_Answer(question=="Something faster than VW TYPE III?" && answer=="No")
	then
		JOptionPane.showInternalMessageDialog(null, "VW TYPE III", "information",JOptionPane.INFORMATION_MESSAGE);
end

rule "Yes_3"
	when 
		q: Question_and_Answer(question=="Something faster than VW TYPE III?" && answer=="Yes")
	then
		Object[] possibleValues = { "No",
									"Yes"};
        Object selectedValue = JOptionPane.showInputDialog(null,"Something faster than PORSHE 914? Choose one",
								 "Input",JOptionPane.INFORMATION_MESSAGE, null,possibleValues, possibleValues[0]);
		Question_and_Answer q1=new Question_and_Answer();
		q1.setQuestion("Something faster than PORSHE 914?");
		q1.setAnswer(selectedValue.toString());
		insert(q1);
end

rule "No_1"
	when 
		q: Question_and_Answer(question=="Something faster than PORSHE 914?" && answer=="No")
	then
		JOptionPane.showInternalMessageDialog(null, "PORSHE 914", "information",JOptionPane.INFORMATION_MESSAGE);
end

rule "Yes_4"
	when 
		q: Question_and_Answer(question=="Something faster than PORSHE 914?" && answer=="Yes")
	then
		JOptionPane.showInternalMessageDialog(null, "DE TOMASO MANGUSTA", "information",JOptionPane.INFORMATION_MESSAGE);
end

//3rd path
rule "New cars have no soul"
	when
		q: Question_and_Answer(question=="Why do you want a classic?" && answer=="New cars have no soul")
	then 
		Object[] possibleValues = { "Easy: ability to drive off a pier into an estuary",
									"Synonym for weird",
									"Soul means the car had an honest job like cop or cabbie",
									"It means the car is often starring in movies",
									"It could mean a pure evil?",
									"Soul is the spirits of 43 dead clowns haunting the car",
									"Soul is the ability to go a million miles with su carbs and lucas electrics",
									"Technically novel",
									"It means riding in it is like sitting on the sofa"};
		Object selectedValue = JOptionPane.showInputDialog(null,"What does soul mean to you? Choose one",
								 "Input",JOptionPane.INFORMATION_MESSAGE, null,possibleValues, possibleValues[0]);
		Question_and_Answer q1=new Question_and_Answer();
		q1.setQuestion("What does soul mean to you?");
		q1.setAnswer(selectedValue.toString());
		insert(q1);
end

rule "Easy: ability to drive off a pier into an estuary"
	when
		q: Question_and_Answer(question=="What does soul mean to you?" && answer=="Easy: ability to drive off a pier into an estuary")
	then
		JOptionPane.showInternalMessageDialog(null, "AMPHICAR","information", JOptionPane.INFORMATION_MESSAGE);
end

rule "Synonym for weird"
	when
		q: Question_and_Answer(question=="What does soul mean to you?" && answer=="Synonym for weird")
	then
		JOptionPane.showInternalMessageDialog(null, "BMW ISETTA, SUBARU 360, MESSERSCHMIDT KABINROLLER","information", JOptionPane.INFORMATION_MESSAGE);
end

rule "Soul means the car had an honest job like cop or cabbie"
	when
		q: Question_and_Answer(question=="What does soul mean to you?" && answer=="Soul means the car had an honest job like cop or cabbie")
	then
		JOptionPane.showInternalMessageDialog(null, "DODGE MONACO, CHEVY CAPRICE, FORD CROWN VIC","information", JOptionPane.INFORMATION_MESSAGE);
end

rule "It means the car is often starring in movies"
	when
		q: Question_and_Answer(question=="What does soul mean to you?" && answer=="It means the car is often starring in movies")
	then
		JOptionPane.showInternalMessageDialog(null, "VW BETTLE, DELOREAN DMC-12","information", JOptionPane.INFORMATION_MESSAGE);
end
	
rule "It could mean a pure evil?"
	when
		q: Question_and_Answer(question=="What does soul mean to you?" && answer=="It could mean a pure evil?")
	then
		JOptionPane.showInternalMessageDialog(null, "PLYMOUTH FURY, BUICK GNX","information", JOptionPane.INFORMATION_MESSAGE);
end
	
rule "Soul is the spirits of 43 dead clowns haunting the car"
	when
		q: Question_and_Answer(question=="What does soul mean to you?" && answer=="Soul is the spirits of 43 dead clowns haunting the car")
	then
		JOptionPane.showInternalMessageDialog(null, "NASH METROPOLITAN","information", JOptionPane.INFORMATION_MESSAGE);
end

rule "Soul is the ability to go a million miles with su carbs and lucas electrics"
	when
		q: Question_and_Answer(question=="What does soul mean to you?" && answer=="Soul is the ability to go a million miles with su carbs and lucas electrics")
	then
		JOptionPane.showInternalMessageDialog(null, "VOLVO P1800","information", JOptionPane.INFORMATION_MESSAGE);
end

rule "Technically novel"
	when
		q: Question_and_Answer(question=="What does soul mean to you?" && answer=="Technically novel")
	then
		Object[] possibleValues = { "They thought they were building a plane",
									"Instead of pistons some metal hamantaschen",
									"Can burn cooking oil",
									"Engine in the wrong place (maybe cooled by wrong stuff)"};
		Object selectedValue = JOptionPane.showInputDialog(null,"Like what? Choose one",
								 "Input",JOptionPane.INFORMATION_MESSAGE, null,possibleValues, possibleValues[0]);
		Question_and_Answer q1=new Question_and_Answer();
		q1.setQuestion("Like what?");
		q1.setAnswer(selectedValue.toString());
		insert(q1);
end

rule "They thought they were building a plane"
	when
		q: Question_and_Answer(question=="Like what?" && answer=="They thought they were building a plane")
	then
		JOptionPane.showInternalMessageDialog(null, "SAAB 96","information", JOptionPane.INFORMATION_MESSAGE);
end

rule "Instead of pistons some metal hamantaschen"
	when
		q: Question_and_Answer(question=="Like what?" && answer=="Instead of pistons some metal hamantaschen")
	then
		JOptionPane.showInternalMessageDialog(null, "MAZDA RX-7","information", JOptionPane.INFORMATION_MESSAGE);
end

rule "Can burn cooking oil"
	when
		q: Question_and_Answer(question=="Like what?" && answer=="Can burn cooking oil")
	then
		JOptionPane.showInternalMessageDialog(null, "MERCEDES BENZ 300TD","information", JOptionPane.INFORMATION_MESSAGE);
end

rule "Engine in the wrong place (maybe cooled by wrong stuff)"
	when
		q: Question_and_Answer(question=="Like what?" && answer=="Engine in the wrong place (maybe cooled by wrong stuff)")
	then
		JOptionPane.showInternalMessageDialog(null, "PORSHE 912, RENAULT ALPINE","information", JOptionPane.INFORMATION_MESSAGE);
end

rule "It means riding in it is like sitting on the sofa"
	when
		q: Question_and_Answer(question=="What does soul mean to you?" && answer=="It means riding in it is like sitting on the sofa")
	then
		Object[] possibleValues = { "No",
									"Yes"};
        Object selectedValue = JOptionPane.showInputDialog(null,"A huge, fast FWD sofa? Choose one",
								 "Input",JOptionPane.INFORMATION_MESSAGE, null,possibleValues, possibleValues[0]);
		Question_and_Answer q1=new Question_and_Answer();
		q1.setQuestion("A huge, fast FWD sofa?");
		q1.setAnswer(selectedValue.toString());
		insert(q1);
end

rule "No_2"
	when
		q: Question_and_Answer(question=="A huge, fast FWD sofa?" && answer=="No")
	then
		JOptionPane.showInternalMessageDialog(null, "LINCOLN TOWN CAR","information", JOptionPane.INFORMATION_MESSAGE);
end

rule "Yes_5"
	when
		q: Question_and_Answer(question=="A huge, fast FWD sofa?" && answer=="Yes")
	then
		JOptionPane.showInternalMessageDialog(null, "OLDS TORNADO","information", JOptionPane.INFORMATION_MESSAGE);
end	
	
//4th path
rule "I prefer the style"
	when
		q: Question_and_Answer(question=="Why do you want a classic?" && answer=="I prefer the style")
	then
		Object[] possibleValues = { "I love chrome and loud shirts", 
        							"Really slow cars that look fast",
        							"I love brass and lanterns",
        							"African dictator",
        							"Like buck Roger's boss's dad",
        							"I love corvairs but live in 3/4 scale universe",
        							"I can only drive cars that are museum-worthy",
        							"Classic german with a touch of pedal confusion",
        							"Working class hero, also beer"};
        Object selectedValue = JOptionPane.showInputDialog(null,"Ok, what kind of style? Choose one",
								 "Input",JOptionPane.INFORMATION_MESSAGE, null,possibleValues, possibleValues[0]);
		Question_and_Answer q1=new Question_and_Answer();
		q1.setQuestion("Ok, what kind of style?");
		q1.setAnswer(selectedValue.toString());
		insert(q1);
end

rule "I love chrome and loud shirts"
	when
		q: Question_and_Answer(question=="Ok, what kind of style?" && answer=="I love chrome and loud shirts")
	then
		JOptionPane.showInternalMessageDialog(null, "'57 CHEVY BEL AIR","information", JOptionPane.INFORMATION_MESSAGE);
end

rule "Really slow cars that look fast"
	when
		q: Question_and_Answer(question=="Ok, what kind of style?" && answer=="Really slow cars that look fast")
	then
		JOptionPane.showInternalMessageDialog(null, "OPEL GT, VW KARMANN GHIA, RENAULT FLORIDE","information", JOptionPane.INFORMATION_MESSAGE);
end

rule "I love brass and lanterns"
	when
		q: Question_and_Answer(question=="Ok, what kind of style?" && answer=="I love brass and lanterns")
	then
		JOptionPane.showInternalMessageDialog(null, "ANYTHING PRE WWI, MAYBE A PACKARD","information", JOptionPane.INFORMATION_MESSAGE);
end

rule "African dictator"
	when
		q: Question_and_Answer(question=="Ok, what kind of style?" && answer=="African dictator")
	then
		JOptionPane.showInternalMessageDialog(null, "MERCEDES BENZ-600","information", JOptionPane.INFORMATION_MESSAGE);
end

rule "Like buck Roger's boss's dad"
	when
		q: Question_and_Answer(question=="Ok, what kind of style?" && answer=="Like buck Roger's boss's dad")
	then
		JOptionPane.showInternalMessageDialog(null, "'59 CADILLAC ELDORDO","information", JOptionPane.INFORMATION_MESSAGE);
end

rule "I love corvairs but live in 3/4 scale universe"
	when
		q: Question_and_Answer(question=="Ok, what kind of style?" && answer=="I love corvairs but live in 3/4 scale universe")
	then
		JOptionPane.showInternalMessageDialog(null, "NSU PRINZ", "information",JOptionPane.INFORMATION_MESSAGE);
end

rule "I can only drive cars that are museum-worthy"
	when
		q: Question_and_Answer(question=="Ok, what kind of style?" && answer=="I can only drive cars that are museum-worthy")
	then
		JOptionPane.showInternalMessageDialog(null, "CITROEN DS. , LAMBORGHINI MIURA, CORD 812, JAGUAR E-TYPE","information", JOptionPane.INFORMATION_MESSAGE);
end

rule "Classic german with a touch of pedal confusion"
	when
		q: Question_and_Answer(question=="Ok, what kind of style?" && answer=="Classic german with a touch of pedal confusion")
	then
		JOptionPane.showInternalMessageDialog(null, "AUDI 100","information", JOptionPane.INFORMATION_MESSAGE);
end

rule "Working class hero, also beer"
	when
		q: Question_and_Answer(question=="Ok, what kind of style?" && answer=="Working class hero, also beer")
	then
		Object[] possibleValues = { "Does your hat say you'd rather push a chevy?", 
        							"What do you want from tires?"};
        Object selectedValue = JOptionPane.showInputDialog(null,"Choose one",
								 "Input",JOptionPane.INFORMATION_MESSAGE, null,possibleValues, possibleValues[0]);
		Question_and_Answer q1=new Question_and_Answer();
		q1.setQuestion("");
		q1.setAnswer(selectedValue.toString());
		insert(q1);
end

rule "Does your hat say you'd rather push a chevy?"
	when
		q: Question_and_Answer(question=="" && answer=="Does your hat say you'd rather push a chevy?")
	then
		Object[] possibleValues = { "Dammit, I lost my hat", 
        							"So it does, friend"};
        Object selectedValue = JOptionPane.showInputDialog(null,"Does your hat say you'd rather push a chevy? Choose one",
								 "Input",JOptionPane.INFORMATION_MESSAGE, null,possibleValues, possibleValues[0]);
		Question_and_Answer q1=new Question_and_Answer();
		q1.setQuestion("Does your hat say you'd rather push a chevy?");
		q1.setAnswer(selectedValue.toString());
		insert(q1);
end

rule "What do you want from tires?"
	when
		q: Question_and_Answer(question=="" && answer=="What do you want from tires?")
	then
		Object[] possibleValues = { "Noise and smoke", 
        							"Noise, smoke and trailer partk's undying respect"};
        Object selectedValue = JOptionPane.showInputDialog(null,"What do you want from tires? Choose one",
								 "Input",JOptionPane.INFORMATION_MESSAGE, null,possibleValues, possibleValues[0]);
		Question_and_Answer q1=new Question_and_Answer();
		q1.setQuestion("What do you want from tires?");
		q1.setAnswer(selectedValue.toString());
		insert(q1);
end

rule "Dammit, I lost my hat"
	when
		q: Question_and_Answer(question=="Does your hat say you'd rather push a chevy?" && answer=="Dammit, I lost my hat")
	then
		JOptionPane.showInternalMessageDialog(null, "AMC-AMX","information", JOptionPane.INFORMATION_MESSAGE);
end

rule "So it does, friend"
	when
		q: Question_and_Answer(question=="Does your hat say you'd rather push a chevy?" && answer=="So it does, friend")
	then
		JOptionPane.showInternalMessageDialog(null, "CHEVY CAMARO", "information",JOptionPane.INFORMATION_MESSAGE);
end

rule "Noise and smoke"
	when
		q: Question_and_Answer(question=="What do you want from tires?" && answer=="Noise and smoke")
	then
		JOptionPane.showInternalMessageDialog(null, "FORD MUSTANG MACH I, FORD MUSTANG,CHEVY C3 CORVETTE","information", JOptionPane.INFORMATION_MESSAGE);
end

rule "Noise, smoke and trailer partk's undying respect"
	when
		q: Question_and_Answer(question=="What do you want from tires?" && answer=="Noise, smoke and trailer partk's undying respect")
	then
		JOptionPane.showInternalMessageDialog(null, "FOX BODY MUSTANG, FORD MUSTANG","information", JOptionPane.INFORMATION_MESSAGE);
end

//5th path
rule "Love speed, hate safety"
	when
		q: Question_and_Answer(question=="Why do you want a classic?" && answer=="Love speed, hate safety")
	then
		Object[] possibleValues = { "Fast and cheep", 
        							"Fake is fine",
        							"I have a death wish",
        							"I love speed and money"};
        Object selectedValue = JOptionPane.showInputDialog(null,"Real speed or just feel speedy? Choose one",
								 "Input",JOptionPane.INFORMATION_MESSAGE, null,possibleValues, possibleValues[0]);
		Question_and_Answer q1=new Question_and_Answer();
		q1.setQuestion("Real speed or just feel speedy?");
		q1.setAnswer(selectedValue.toString());
		insert(q1);
end

rule "Fast and cheep"
	when
		q: Question_and_Answer(question=="Real speed or just feel speedy?" && answer=="Fast and cheep")
	then
		JOptionPane.showInternalMessageDialog(null, "DODGE OMNI GLH","information", JOptionPane.INFORMATION_MESSAGE);
end

rule "Fake is fine"
	when
		q: Question_and_Answer(question=="Real speed or just feel speedy?" && answer=="Fake is fine")
	then
		JOptionPane.showInternalMessageDialog(null, "DATSUN S10, MINI COOPER, Mk1 VW GOLF GTI, HONDA CRX","information", JOptionPane.INFORMATION_MESSAGE);
end

rule "I have a death wish"
	when
		q: Question_and_Answer(question=="Real speed or just feel speedy?" && answer=="I have a death wish")
	then
		Object[] possibleValues = { "Crushed by V8 in tiny space", 
        							"Electrocuted by wiper switch",
        							"Blaze of glory",
        							"Car, tree",
        							"Run of out talent,off cliff"};
        Object selectedValue = JOptionPane.showInputDialog(null,"How do you want to go? Choose one",
								 "Input",JOptionPane.INFORMATION_MESSAGE, null,possibleValues, possibleValues[0]);
		Question_and_Answer q1=new Question_and_Answer();
		q1.setQuestion("How do you want to go?");
		q1.setAnswer(selectedValue.toString());
		insert(q1);
end

rule "Crushed by V8 in tiny space"
	when
		q: Question_and_Answer(question=="How do you want to go?" && answer=="Crushed by V8 in tiny space")
	then
		JOptionPane.showInternalMessageDialog(null, "SUNBEAM TIGER", "information",JOptionPane.INFORMATION_MESSAGE);
end

rule "Electrocuted by wiper switch"
	when
		q: Question_and_Answer(question=="How do you want to go?" && answer=="Electrocuted by wiper switch")
	then
		JOptionPane.showInternalMessageDialog(null, "JAGUAR E-TYPE","information", JOptionPane.INFORMATION_MESSAGE);
end

rule "Blaze of glory"
	when
		q: Question_and_Answer(question=="How do you want to go?" && answer=="Blaze of glory")
	then
		JOptionPane.showInternalMessageDialog(null, "FERRARI TESTAROSA","information", JOptionPane.INFORMATION_MESSAGE);
end

rule "Car, tree"
	when
		q: Question_and_Answer(question=="How do you want to go?" && answer=="Car, tree")
	then
		JOptionPane.showInternalMessageDialog(null, "CAMARO IROC-Z, PLYMOUTH ROAD RUNNER","information", JOptionPane.INFORMATION_MESSAGE);
end

rule "Run of out talent,off cliff"
	when
		q: Question_and_Answer(question=="How do you want to go?" && answer=="Run of out talent,off cliff")
	then
		JOptionPane.showInternalMessageDialog(null, "PORSHE SPYDER", "information",JOptionPane.INFORMATION_MESSAGE);
end

rule "I love speed and money"
	when
		q: Question_and_Answer(question=="Real speed or just feel speedy?" && answer=="I love speed and money")
	then
		Object[] possibleValues = { "Some kind of duke and I rally", 
        							"My goal is to drive my childhood bedroom posters",
        							"I have a weird fetish where I like people asking -Is it a replica?"};
        Object selectedValue = JOptionPane.showInputDialog(null,"Great, who are you? Choose one",
								 "Input",JOptionPane.INFORMATION_MESSAGE, null,possibleValues, possibleValues[0]);
		Question_and_Answer q1=new Question_and_Answer();
		q1.setQuestion("Great, who are you?");
		q1.setAnswer(selectedValue.toString());
		insert(q1);
end

rule "Some kind of duke and I rally"
	when
		q: Question_and_Answer(question=="Great, who are you?" && answer=="Some kind of duke and I rally")
	then
		JOptionPane.showInternalMessageDialog(null, "LANCIA STARTOS", "information",JOptionPane.INFORMATION_MESSAGE);
end

rule "My goal is to drive my childhood bedroom posters"
	when
		q: Question_and_Answer(question=="Great, who are you?" && answer=="My goal is to drive my childhood bedroom posters")
	then
		JOptionPane.showInternalMessageDialog(null, "LAMBORGHINI COUNTACH, FERRARI 250 GTO","information", JOptionPane.INFORMATION_MESSAGE);
end

rule "I have a weird fetish where I like people asking -Is it a replica?"
	when
		q: Question_and_Answer(question=="Great, who are you?" && answer=="I have a weird fetish where I like people asking -Is it a replica?")
	then
		JOptionPane.showInternalMessageDialog(null, "AC COBRA, PORSHE 356 SPEEDSTER","information", JOptionPane.INFORMATION_MESSAGE);
end